### ISSUE TITLE
Quotes causing an issue

### ISSUE THREAD

**Issue by sumgr0** [KarimPwnz/waybacked#1]
Thanks for the this tool.

While testing it for a single and multiple root domains, the quote seems to be causing and issue.

![image](https://user-images.githubusercontent.com/11391119/146157156-d4f65a62-69c0-4346-8911-daa7fac0fc3e.png)

Similarly when having a file with terms like:
*.target1.com/*
*.target2.com/*

Does not yield any results.

**Comment by amalmurali47** [comment]
@sumgr0 I believe this is due to shell expansion. Double-quotes will interpolate wildcards and other shell characters, but single-quotes won't. Can you try wrapping the search query with single-quotes? For example: `waybacked '*.grammarly.com/*'`?

**Comment by KarimPwnz** [comment]
Hey,

I really appreciate you filing this issue—it is the first one!

I believe the quotes problem is simple [zshell expansion](https://zsh.sourceforge.io/Doc/Release/Expansion.html) and has nothing to do with the tool itself. All you need to do is wrap your search query in single quotes: `waybacked '*.grammarly.com/*'`.

Regarding the file issue, I am unsure what the case is. Perhaps the search query is not comprehensive, so try the following instead:
```
*.target1.com/*
*.target2.com/*
```
If that doesn't work, do share the example targets.

Let me know if I've answered your concerns.

Thanks,
Karim Rahal

**Comment by sumgr0** [comment]
Thank you for the quick revert.

For the single target the single and double quotes are working, just wanted to check if its possible without the quotes

For the file, the MD formatting removed my \*'s from the beginning and end of the root domains. 

So I was saving the root domains as "*.target1.com/*" along with the quotes in the file, which did not return any output. However, when saved the file without the quotes it worked.

All seems to working good now. Shall be carrying out few more tests and then integrate this into my workflow.

Thanks again.

**Comment by KarimPwnz** [comment]
Awesome! Glad to hear you're looking to integrate this into your workflow; keep me updated in case any other issues arise.
